twitter_output_file = "./output/twitter/twitter_output.txt"

twitter_original_graph_pickel_file = "./output/twitter/twitter_original_graph_pickel_file.pkl"
twitter_bipartite_graph_pickel_file = "./output/twitter/twitter_bipartite_graph_pickel_file.pkl"
twitter_isomap_pkl = "./output/isomap/twitter_isomap.pkl"
twitter_hope_pkl = "./output/hope/twitter_hope.pkl"
twitter_poincare_pkl = "./output/twitter/twitter_poincare_pkl.pkl"
twitter_2D_poincare_pkl = "./output/twitter/twitter_2D_poincare_pkl.pkl"
twitter_2D_poincare_label_pkl = "./output/twitter/twitter_2D_poincare_label_pkl.pkl"
twitter_2D_poincare_node_colors_pkl = "./output/twitter/twitter_2D_poincare_node_colors_pkl.pkl"
twitter_2D_poincare_spectral_clustering_pickel = "./output/twitter/twitter_2D_poincare_spectral_clustering_pickel.pkl"
twitter_2D_poincare_spectral_colors_pickel = "./output/twitter/twitter_2D_poincare_spectral_colors_pickel.pkl"
twitter_2D_poincare_spectral_clustering_precomputed_pickel = "./output/twitter/twitter_2D_poincare_spectral_clustering_precomputed_pickel.pkl"
twitter_2D_poincare_spectral_colors_precomputed_pickel = "./output/twitter/twitter_2D_poincare_spectral_colors_precomputed_pickel.pkl"
twitter_2D_poincare_spectral_clustering_precomputed_graph_based_pickel = "./output/twitter/twitter_2D_poincare_spectral_clustering_precomputed_graph_based_pickel.pkl"
twitter_2D_poincare_spectral_colors_precomputed_graph_based_pickel = "./output/twitter/twitter_2D_poincare_spectral_colors_precomputed_graph_based_pickel.pkl"
twitter_2D_poincare_DBSCAN_pickel = "./output/twitter/twitter_2D_poincare_DBSCAN_pickel.pkl"
twitter_2D_poincare_DBSCAN_colors_pickel = "./output/twitter/twitter_2D_poincare_DBSCAN_colors_pickel.pkl"


inputfile = "./resource/congress_network_data.json"

twitter_positive_rating_twitter_node_embedding ="./output/node2vec/twitter_positive_rating_twitter_node_embedding.png"
twitter_negative_rating_twitter_node_embedding = "./output/node2vec/twitter_negative_rating_twitter_node_embedding.png"
twitter_source_node_twitter_node_embedding = "./output/node2vec/twitter_source_node_twitter_node_embedding.png"
twitter_TSNE_bipartite_node_embedding_scatter_plot = "./output/node2vec/twitter_TSNE_bipartite_node_embedding_scatter_with_normal_nodes.png"
twitter_bipartite_graph_name = "./output/node2vec/twitter_bipartite_graph_network.png"
twitter_node2vec = "./output/node2vec/twitter_node2vec.png"

twitter_isomap = "./output/isomap_1/twitter_isomap.png"
twitter_positive_rating_isomap ="./output/isomap_1/twitter_positive_rating_isomap.png"
twitter_negative_rating_isomap = "./output/isomap_1/twitter_negative_rating_isomap.png"
twitter_source_node_isomap = "./output/isomap_1/twitter_source_node_isomap.png"
twitter_isomap_2D = "./output/isomap_1/twitter_isomap_2D.png"

twitter_hope_2D = "./output/hope_1/twitter_hope_2D.png"
twitter_hope = "./output/hope_1/twitter_hope.png"
twitter_positive_rating_hope ="./output/hope_1/twitter_positive_rating_hope.png"
twitter_negative_rating_hope = "./output/hope_1/twitter_negative_rating_hope.png"
twitter_source_node_hope = "./output/hope_1/twitter_source_node_hope.png"
twitter_hope_2D = "./output/hope_1/twitter_hope_2D.png"


twitter_TSNE_bipartite_node_embedding_title = "Bitcoin Tripartite Node Embedding using TSNE"
twitter_bipartite_graph_title = 'Sign Bitcoin Tripatite Graph'
twitter_isomap_title = "Bitcoin Tripartite Node Embedding using ISOMAP"
twitter_hope_title = "Bitcoin Tripartite Node Embedding using HOPE"

twitter_poincare = "./output/twitter/twitter_poincare.png"
twitter_poincare_title = "Bitcoin Tripartite Node Embedding using Poincare"
twitter_poincare = "./output/twitter/twitter_poincare.png"
twitter_positive_rating_poincare ="./output/twitter/twitter_positive_rating_poincare.png"
twitter_negative_rating_poincare = "./output/twitter/twitter_negative_rating_poincare.png"
twitter_source_node_poincare = "./output/twitter/twitter_source_node_poincare.png"
twitter_poincare_1 ="./output/twitter/twitter_poincare_1.png"
twitter_poincare_2 = "./output/twitter/twitter_poincare_2.png"
twitter_poincare_2D_Visualization = "./output/twitter/twitter_poincare_2D_Visualization.png"
twitter_poincare_soucre_2D_Visualization = "./output/twitter/twitter_poincare_soucre_2D_Visualization.png"
twitter_poincare_target_2D_Visualization = "./output/twitter/twitter_poincare_target_2D_Visualization.png"
twitter_poincare_2D_spectral_Visualization = "./output/twitter/twitter_poincare_2D_spectral_Visualization.png"
twitter_poincare_2D_spectral_precomputed_Visualization = "./output/twitter/twitter_poincare_2D_spectral_precomputed_Visualization.png"
twitter_poincare_2D_spectral_precomputed_graph_based_Visualization = "./output/twitter/twitter_poincare_2D_spectral_precomputed_graph_based_Visualization.png"
twitter_poincare_2D_DBSCAN_Visualization = "./output/twitter/twitter_poincare_2D_DBSCAN_Visualization.png"
twitter_bipartite_graph_title = "./output/twitter/twitter_graph_title.png"
twitter_tsne_poincare = "./output/twitter/twitter_poincare.png"
twitter_positive_rating_poincare = "./output/twitter/twitter_positive_rating_poincare.png"
twitter_source_node_poincare = "./output/twitter/twitter_source_node_poincare.png"
twitter_poincare_2 = "./output/twitter/twitter_poincare_2.png"

twitter_edges_csv = "./output/twitter/twitter_edges_csv.csv"
twitter_graph_info_csv = "./output/twitter/twitter_graph_info_csv.csv"
no_of_clusters = 25

twitter_poincare_title = "Twitter TSNE"